"""Added auth user model

Revision ID: 04d9461f0eef
Revises: 
Create Date: 2022-09-13 16:55:13.309715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04d9461f0eef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_user")
    # ### end Alembic commands ###
