"""Added task and time log models

Revision ID: 0cced11845fb
Revises: 04d9461f0eef
Create Date: 2022-09-14 15:06:23.013970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cced11845fb"
down_revision = "04d9461f0eef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )
    # noinspection PyTypeChecker
    op.create_table(
        "time_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_reported", sa.Numeric(precision=2), nullable=False),
        sa.Column("date_reported", sa.Date(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["reporter_id"], ["auth_user.id"], ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_log")
    op.drop_table("task")
    # ### end Alembic commands ###
