"""Added time log model

Revision ID: 22c8122a93fd
Revises: 04d9461f0eef
Create Date: 2022-09-13 17:11:50.048232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22c8122a93fd"
down_revision = "04d9461f0eef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_reported", sa.Numeric(precision=2), nullable=False),
        sa.Column("date_reported", sa.Date(), nullable=False),
        sa.Column("task_uid", sa.String(32), nullable=False),
        sa.Column("task_title", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_log")
    # ### end Alembic commands ###
